stages:
  - deploy

deploy_to_github:
  stage: deploy
  script:
    - git config --global user.email "zamarin2202200315@gmail.com"
    - git config --global user.name "Zamarin-Aleksey"
    - git remote add github "https://Zamarin-Aleksey:${GITHUB_TOKEN}@github.com/testorgzmrn/test_repo.git"
    - git push github main --force
  only:
    - main
